name = "Minecraft Mod Pack"
author = "strawberrypip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3ee66869524beec576382dfefe094b3586e27f2b98da7d06367d3f448e22de8"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
