name = "Minecraft Mod Pack"
author = "strawberrypip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c39aff7c4f259d0937f8c4e9becb176d3b68332a9fd6d643354fb47c6066447c"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
