name = "Minecraft Mod Pack"
author = "strawberrypip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "943c6d15e8075f86f0d283f3539608cdbe4b00b5c34140c821458e0233fe63b5"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
